[workspace]
exclude = [
  "crates/node_binding",
] # Avoid including node binding, since feature unification will cause an linking issue. See: https://doc.rust-lang.org/cargo/reference/features.html#feature-unification
members = ["crates/*", "xtask"]

[profile.dev]
debug       = 2
incremental = true

[profile.release]
codegen-units = 1
debug         = false
incremental   = true
lto           = false
opt-level     = 3


[workspace.dependencies]
napi              = { version = "=2.10.6" }
napi-build        = { version = "=2.0.1" }
napi-derive       = { version = "=2.9.4" }
napi-sys          = { version = "=2.2.2" }
preset_env_base   = { git = "https://github.com/IWANABETHATGUY/swc", branch = "chore/better-string-cache", version = "0.4.0" }
rustc-hash        = { version = "1.1.0" }
serde             = "1.0.152"
serde_json        = "1.0.91"
swc_core          = { git = "https://github.com/IWANABETHATGUY/swc", branch = "chore/better-string-cache", default-features = false }
swc_css           = { git = "https://github.com/IWANABETHATGUY/swc", branch = "chore/better-string-cache" }
swc_html          = { git = "https://github.com/IWANABETHATGUY/swc", branch = "chore/better-string-cache", version = "0.109.10" }
swc_html_minifier = { git = "https://github.com/IWANABETHATGUY/swc", branch = "chore/better-string-cache", version = "0.106.10" }

tracing = "0.1.34"
